[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "W",  # pycodestyle warnings
]
ignore = [
    "E203",  # whitespace before ':'
    "E501",  # line too long
]