[tool.ruff]
line-length = 88

[tool.black]
# Default line length for black
line-length = 88
# Specify directories to ignore (using glob patterns)
exclude = '''
(
    /(
        \.venv|
        \.venv-.*
    )/
)
'''

[tool.isort]
# Ensure consistent with black's line length
line_length = 88
# Choose a multi-line output style compatible with black (3 means new line before import names)
multi_line_output = 3
# Ensure trailing commas for consistency with black
include_trailing_comma = true 
# Specify directories to ignore
skip = [
    ".venv",
    ".venv-*"
]
